# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TikiSdkExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TikiSdkExample

  pod 'TikiSdk', :path => '../../'
  pod 'TikiSdkRelease', :configuration => 'Release', :path => '../../'
  pod 'TikiSdkDebug', :configuration => 'Debug', :path => '../../'

end
