name: Project

on:
  pull_request:
    types:
      - opened
      - reopened
      - converted_to_draft
      - ready_for_review
      - review_requested
      - review_request_removed
  issues:
    types:
      - opened

jobs:
  add-pr:
    uses: tiki/.github/.github/workflows/project.yml@main
    secrets: inherit
